### ISSUE TITLE
Error message when no waiver available for a Work Party

### ISSUE THREAD

**Issue by ninetaLogik** [washingtontrails/vms#110]
When a work party has no waiver the link to the waiver from the confirmation email shows this error:
{"code": 500, "detail": "'NoneType' object is not iterable", "title": "TypeError"} 

Example link:
http://staging.wta.org:6543/workparty/a2eK0000000wLW4/waiver

A more descriptive error message would be preferable to inform us there is no waiver for this wp.

**Comment by cewing** [comment]
On a related note, when trying to view the sign-in sheet for such a work party we get the same error.  Here's the traceback:

```
Traceback (most recent call last):
  File "/Users/cewing/.buildout/eggs/pyramid-1.5.2-py2.7.egg/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/Users/cewing/.buildout/eggs/pyramid-1.5.2-py2.7.egg/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "/Users/cewing/.buildout/eggs/pyramid-1.5.2-py2.7.egg/pyramid/config/views.py", line 245, in _secured_view
    return view(context, request)
  File "/Users/cewing/.buildout/eggs/pyramid-1.5.2-py2.7.egg/pyramid/config/views.py", line 355, in rendered_view
    result = view(context, request)
  File "/Users/cewing/projects/jazkarta/wta/vms/src/vms/views.py", line 407, in workparty_registrations
    record['registered_by'][:15] == my_reg['id'] and
TypeError: 'NoneType' object has no attribute '__getitem__'
2015-05-28 14:41:34,159 ERROR [vms][Dummy-2] 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/Users/cewing/.buildout/eggs/pyramid-1.5.2-py2.7.egg/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/Users/cewing/.buildout/eggs/pyramid-1.5.2-py2.7.egg/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "/Users/cewing/.buildout/eggs/pyramid-1.5.2-py2.7.egg/pyramid/config/views.py", line 245, in _secured_view
    return view(context, request)
  File "/Users/cewing/.buildout/eggs/pyramid-1.5.2-py2.7.egg/pyramid/config/views.py", line 355, in rendered_view
    result = view(context, request)
  File "/Users/cewing/projects/jazkarta/wta/vms/src/vms/views.py", line 407, in workparty_registrations
    record['registered_by'][:15] == my_reg['id'] and
TypeError: 'NoneType' object has no attribute '__getitem__'
```

catching both `NotFoundError` and `TypeError` [here](https://github.com/washingtontrails/vms/blob/master/src/vms/register.py#L544) appears to silence the failure.

**Comment by davisagli** [comment]
Those are two different errors, but they're now both fixed.
