### ISSUE TITLE
Work Party Roster for Weekend Work Party needs to show which day / volunteer

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#213]
For week end work parties the CL Roster (Print and Online) needs to show which day each volunteer has signed up for, or at least for those who have selected only one of the 2 days to indicate which day the will be attending.

Here is a link to the Alec's Test Party, Sat, Aug 8, 2015 – Sun, Aug 9, 2015
http://staging.wta.org:6543/workparty/a2eK0000000wM9R/print-roster.html

**Comment by davisagli** [comment]
@cguardia here's another good one. In the roster table in the Days column, we need to list the actual days (e.g. "Sat, Sun") instead of just the count of how many days.  For both the print roster and the one on the Crew Corner tab.

**Comment by davisagli** [comment]
This works now.

**Comment by WaBirder57** [comment]
@davisagli This update needs to be made to the printer roster.  It shows on Crew Corner just fine.

**Comment by cewing** [comment]
@davisagli: this is ready for review, and hopefully to be merged and closed.

**Comment by davisagli** [comment]
@cewing I tried it on http://staging.wta.org:6543/workparty/a2eK00000000jOR/ and got this traceback:

```
Traceback (most recent call last):
  File "/usr/local/pyramid/vms/eggs/pyramid-1.5.2-py2.7.egg/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/usr/local/pyramid/vms/eggs/pyramid_exclog-0.7-py2.7.egg/pyramid_exclog/__init__.py", line 115, in exclog_tween
    _handle_error(request, getLogger, get_message)
  File "/usr/local/pyramid/vms/eggs/pyramid_exclog-0.7-py2.7.egg/pyramid_exclog/__init__.py", line 111, in exclog_tween
    return handler(request)
  File "/usr/local/pyramid/vms/eggs/pyramid-1.5.2-py2.7.egg/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "/usr/local/pyramid/vms/eggs/pyramid-1.5.2-py2.7.egg/pyramid/config/views.py", line 245, in _secured_view
    return view(context, request)
  File "/usr/local/pyramid/vms/eggs/pyramid-1.5.2-py2.7.egg/pyramid/config/views.py", line 355, in rendered_view
    result = view(context, request)
  File "/usr/local/pyramid/vms/src/vms/views.py", line 906, in workparty_signin_sheet
    "registrations": sorted([r['contact'] for r in records
  File "/usr/local/pyramid/vms/src/vms/utils.py", line 372, in add_days_attending
    reg_days = reg.get('days_registered_for', '').split(';')
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by cewing** [comment]
oh darn.  Means that the key is there, but None.  Will fix now

**Comment by cewing** [comment]
Should be fixed now, @davisagli, see 8e66156de0ee90dcecb86959540172fedc5ef743

**Comment by davisagli** [comment]
Works now.

**Comment by WaBirder57** [comment]
Looks Great, thanks. @cewing I'm going to open a new ticket with a few tweaks to this sign in sheet layout.
