### ISSUE TITLE
trip report submission error

### ISSUE THREAD

**Issue by KindraRamos** [washingtontrails/vms#459]
When you try to enter trip reports as a My Backpack user:

TypeError("'NoneType' object has no attribute '__getitem__'",) (Also, the following error occurred while attempting to render the standard error message, please see the event log for full details: 'NoneType' object has no attribute '__getitem__')

shows up in all the browsers I tried.

**Comment by davisagli** [comment]
Full stack trace:

```
Traceback (most recent call last):
  File "/usr/local/plone/buildout-cache/eggs/Zope2-2.13.21-py2.7.egg/OFS/SimpleItem.py", line 242, in raise_standardErrorMessage
    v = s(**kwargs)
  File "/usr/local/plone/buildout-cache/eggs/Products.CMFCore-2.2.7-py2.7.egg/Products/CMFCore/FSPythonScript.py", line 127, in __call__
    return Script.__call__(self, *args, **kw)
  File "/usr/local/plone/buildout-cache/eggs/Zope2-2.13.21-py2.7.egg/Shared/DC/Scripts/Bindings.py", line 322, in __call__
    return self._bindAndExec(args, kw, None)
  File "/usr/local/plone/buildout-cache/eggs/Zope2-2.13.21-py2.7.egg/Shared/DC/Scripts/Bindings.py", line 359, in _bindAndExec
    return self._exec(bound_data, args, kw)
  File "/usr/local/plone/buildout-cache/eggs/Products.PythonScripts-2.13.2-py2.7.egg/Products/PythonScripts/PythonScript.py", line 344, in _exec
    result = f(*args, **kw)
  File "Script (Python)", line 34, in standard_error_message
  File "/usr/local/plone/buildout-cache/eggs/Zope2-2.13.21-py2.7.egg/Shared/DC/Scripts/Bindings.py", line 322, in __call__
    return self._bindAndExec(args, kw, None)
  File "/usr/local/plone/buildout-cache/eggs/Zope2-2.13.21-py2.7.egg/Shared/DC/Scripts/Bindings.py", line 359, in _bindAndExec
    return self._exec(bound_data, args, kw)
  File "/usr/local/plone/buildout-cache/eggs/Products.CMFCore-2.2.7-py2.7.egg/Products/CMFCore/FSPageTemplate.py", line 237, in _exec
    result = self.pt_render(extra_context=bound_names)
  File "/usr/local/plone/buildout-cache/eggs/Products.CMFCore-2.2.7-py2.7.egg/Products/CMFCore/FSPageTemplate.py", line 177, in pt_render
    self, source, extra_context
  File "/usr/local/plone/buildout-cache/eggs/Zope2-2.13.21-py2.7.egg/Products/PageTemplates/PageTemplate.py", line 79, in pt_render
    showtal=showtal)
  File "/usr/local/plone/buildout-cache/eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 132, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations
  File "/usr/local/plone/buildout-cache/eggs/five.pt-2.2.3-py2.7.egg/five/pt/engine.py", line 93, in __call__
    return self.template.render(**kwargs)
  File "/usr/local/plone/buildout-cache/eggs/z3c.pt-2.2.3-py2.7.egg/z3c/pt/pagetemplate.py", line 149, in render
    return base_renderer(**context)
  File "/usr/local/plone/buildout-cache/eggs/Chameleon-2.22-py2.7.egg/chameleon/zpt/template.py", line 258, in render
    return super(PageTemplate, self).render(**vars)
  File "/usr/local/plone/buildout-cache/eggs/Chameleon-2.22-py2.7.egg/chameleon/template.py", line 191, in render
    raise_with_traceback(exc, tb)
  File "/usr/local/plone/buildout-cache/eggs/Chameleon-2.22-py2.7.egg/chameleon/template.py", line 171, in render
    self._render(stream, econtext, rcontext)
  File "788af3c8845acb4d4c34ea3f7732952d.py", line 1780, in render
  File "c18b07b55c48df33db403e44131b2a08.py", line 1373, in render_master
  File "/usr/local/plone/buildout-cache/eggs/z3c.pt-2.2.3-py2.7.egg/z3c/pt/expressions.py", line 58, in render_content_provider
    cp.update()
  File "/usr/local/plone/buildout-cache/eggs/zope.viewlet-3.7.2-py2.7.egg/zope/viewlet/manager.py", line 112, in update
    self._updateViewlets()
  File "/usr/local/plone/buildout-cache/eggs/zope.viewlet-3.7.2-py2.7.egg/zope/viewlet/manager.py", line 118, in _updateViewlets
    viewlet.update()
  File "/usr/local/plone/buildout-cache/eggs/Products.Carousel-2.2.1-py2.7.egg/Products/Carousel/browser/viewlet.py", line 68, in update
    banners = carousel.getBanners()
  File "/usr/local/plone/buildout-cache/eggs/Products.Carousel-2.2.1-py2.7.egg/Products/Carousel/browser/folder.py", line 47, in getBanners
    'sort_on': 'getObjPositionInParent',
  File "/usr/local/plone/buildout-cache/eggs/collective.indexing-1.8-py2.7.egg/collective/indexing/monkey.py", line 92, in searchResults
    autoFlushQueue(hint='restricted search', request=REQUEST, **kw)
  File "/usr/local/plone/buildout-cache/eggs/collective.indexing-1.8-py2.7.egg/collective/indexing/utils.py", line 57, in autoFlushQueue
    return processQueue()
  File "/usr/local/plone/buildout-cache/eggs/collective.indexing-1.8-py2.7.egg/collective/indexing/queue.py", line 36, in processQueue
    processed = queue.process()
  File "/usr/local/plone/buildout-cache/eggs/collective.indexing-1.8-py2.7.egg/collective/indexing/queue.py", line 147, in process
    util.reindex(obj, attributes)
  File "/usr/local/plone/buildout-cache/eggs/collective.indexing-1.8-py2.7.egg/collective/indexing/indexer.py", line 86, in reindex
    reindex(obj, attributes)
  File "/usr/local/plone/buildout-cache/eggs/collective.indexing-1.8-py2.7.egg/collective/indexing/indexer.py", line 62, in reindex
    op(obj, attributes or [])
  File "/usr/local/plone/staging/src/Products.Archetypes/Products/Archetypes/CatalogMultiplex.py", line 124, in reindexObject
    c.catalog_object(self, url, idxs=lst)
  File "/usr/local/plone/buildout-cache/eggs/Products.CMFPlone-4.2.7-py2.7.egg/Products/CMFPlone/CatalogTool.py", line 394, in catalog_object
    update_metadata, pghandler=pghandler)
  File "/usr/local/plone/buildout-cache/eggs/Products.ZCatalog-3.0.2-py2.7.egg/Products/ZCatalog/ZCatalog.py", line 476, in catalog_object
    update_metadata=update_metadata)
  File "/usr/local/plone/buildout-cache/eggs/Products.ZCatalog-3.0.2-py2.7.egg/Products/ZCatalog/Catalog.py", line 341, in catalogObject
    index = self.updateMetadata(object, uid, None)
  File "/usr/local/plone/buildout-cache/eggs/Products.ZCatalog-3.0.2-py2.7.egg/Products/ZCatalog/Catalog.py", line 292, in updateMetadata
    newDataRecord = self.recordify(object)
  File "/usr/local/plone/buildout-cache/eggs/Products.ZCatalog-3.0.2-py2.7.egg/Products/ZCatalog/Catalog.py", line 415, in recordify
    attr = attr()
  File "/usr/local/plone/staging/src/wta.content/wta/content/content/tripreport.py", line 685, in isTrailheadSpecified
    """ Delegate to a general policy for location equivalence """
  File "/usr/local/plone/staging/src/wta.content/wta/content/browser/maps.py", line 82, in hasValidNonDefaultLocation
    current = self._currentLocation()
  File "/usr/local/plone/staging/src/wta.content/wta/content/browser/maps.py", line 73, in _currentLocation
    if isinstance(current[0], basestring):
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by davisagli** [comment]
Sorry, I broke this while working on the mapping of trip reports, and fixed it but forgot to deploy the fix. Should work now.
