### ISSUE TITLE
Bulk sync of trip reports stats not working yet

### ISSUE THREAD

**Issue by davisagli** [washingtontrails/vms#478]
The code to upload a bulk update of trip report stats each night is not working yet on the live server. It needs some adjustment to handle more than 10000 contacts which is the Salesforce limit on batch size.

Traceback:
```
Traceback (most recent call last):
  File "/usr/local/plone/buildout-cache/eggs/celery-3.1.19-py2.7.egg/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/plone/buildout-cache/eggs/celery-3.1.19-py2.7.egg/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/plone/zeocluster/src/collective.celery/collective/celery/__init__.py", line 45, in new_func
    return runner()
  File "/usr/local/plone/zeocluster/src/collective.celery/collective/celery/functionrunner.py", line 60, in __call__
    result = self.func(*args, **kw)
  File "/usr/local/plone/zeocluster/src/wta.content/wta/content/sf/tasks.py", line 308, in upload_trip_reports_to_salesforce
    batch = bulk.post_bulk_batch(job, csv_iter)
  File "/usr/local/plone/buildout-cache/eggs/salesforce_bulk-1.1.0-py2.7.egg/salesforce_bulk/salesforce_bulk.py", line 294, in post_bulk_batch
    resp = requests.post(uri, data=csv_generator, headers=headers)
  File "/usr/local/plone/buildout-cache/eggs/requests-2.7.0-py2.7.egg/requests/api.py", line 109, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/plone/buildout-cache/eggs/requests-2.7.0-py2.7.egg/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/plone/buildout-cache/eggs/requests-2.7.0-py2.7.egg/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/plone/buildout-cache/eggs/requests-2.7.0-py2.7.egg/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/plone/buildout-cache/eggs/requests-2.7.0-py2.7.egg/requests/adapters.py", line 390, in send
    for i in request.body:
  File "/usr/local/plone/buildout-cache/eggs/salesforce_bulk-1.1.0-py2.7.egg/salesforce_bulk/csv_adapter.py", line 19, in next
    row = self.source.next()
AttributeError: 'list' object has no attribute 'next'
```

**Comment by davisagli** [comment]
This appears to have run successfully last night.

@mscholtz I'd like to check the bulk data results in the Salesforce UI to see how many records failed (which might give us a sense of the extent of the problem with duplicate Website Member Ids), but the VMS App user can't see that page in Setup. Can you give me access to this?

**Comment by mscholtz** [comment]
@WaBirder57 I think this is actually a question for you.  I don't want to change the profile of the VMS App user.  But do you have the licenses to temporarily make a sysadmin user account for David?  (If not, I can share our login with him, but would prefer if he had his own.)

**Comment by WaBirder57** [comment]
OK, David is set up with a license I borrowed from another person.  david+wta@glicksoftware.com is the users name.

**Comment by davisagli** [comment]
This finally worked last night. Of course it did not work for users with duplicated member ids. Also it fails if the trip report name is too long for the field it goes into, so I should probably truncate it.

**Comment by WaBirder57** [comment]
Here is a screenshot from my Galaxy S5. The Galaxy S5 uses a 5.1-inch AMOLED display with a pin sharp full-HD resolution of 1920 x 1080 and 432 pixels per inch (PPI). 

The page displays a bit to wide and I have to slide the image back and forth in my phone's FireFox browser to see everything.  I'm not sure how this sizing works nor if this is a big fix.  I marked ticket low priority but nice to have.

![samsungs5 screenshot_2016-01-05-11-17-25](https://cloud.githubusercontent.com/assets/8312206/12125172/b39b4e38-b39e-11e5-902d-707b60d9ed15.png)

**Comment by davisagli** [comment]
I think you meant to add that to #429

**Comment by WaBirder57** [comment]
@davisagli @mscholtz We should set the SF Most Recent Trip report field to 255 characters and then have the data from Plone truncate if it is longer than that.

**Comment by mscholtz** [comment]
@WaBirder57 do you want to re-open this ticket?  or create a new ticket for that?  I would prefer the latter, but either one is OK by me.  Please make it high priority if you want it done before launch.

@davisagli let me know if we need to coordinate here or if I can just go ahead.

**Comment by davisagli** [comment]
I think the field is already limited to 255 characters in Salesforce, and I added the truncation yesterday so that will be in place the next time I deploy...so we can probably just leave this closed.

**Comment by WaBirder57** [comment]
I have created #516 for this last item.  Thanks.
