### ISSUE TITLE
VMS: Waitlist Acceptance E-mail Links Broken

### ISSUE THREAD

**Issue by ebskopin** [washingtontrails/vms#489]
When clicking the "Accept the invitation" link on a work party wait list e-mail I receive the following error:
![image](https://cloud.githubusercontent.com/assets/14843712/11732431/f9fd7068-9f58-11e5-99fd-123fb864d30b.png)

For the following work party: https://cs9.salesforce.com/a2eK00000000iam

**Comment by davisagli** [comment]
Full traceback is:
```
2015-12-11 11:05:30,231 ERROR [exc_logger][waitress] http://staging.wta.org:6543/workparty/a2eK00000000iam/confirm?r=a2oK00000028j3V
Traceback (most recent call last):
  File "/usr/local/pyramid/vms/eggs/pyramid_exclog-0.7-py2.7.egg/pyramid_exclog/__init__.py", line 111, in exclog_tween
    return handler(request)
  File "/usr/local/pyramid/vms/eggs/pyramid-1.5.2-py2.7.egg/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "/usr/local/pyramid/vms/eggs/pyramid-1.5.2-py2.7.egg/pyramid/config/views.py", line 355, in rendered_view
    result = view(context, request)
  File "/usr/local/pyramid/vms/src/vms/register.py", line 807, in handle_confirm_invitation
    for o in registrations if o['registered_by'] is not None]
TypeError: string indices must be integers
```

**Comment by davisagli** [comment]
@cewing @cguardia could one of you take this one? I think the problem is that it needs to iterate over registrations.values() instead of registrations

**Comment by davisagli** [comment]
@ebskopin give this another try now.

**Comment by ebskopin** [comment]
Tried again and got a new error:
![image](https://cloud.githubusercontent.com/assets/14843712/11757805/36972256-a019-11e5-87aa-9a6d8996cd79.png)

**Comment by ebskopin** [comment]
checking back in on this

**Comment by davisagli** [comment]
Sorry, we lost track of this one since it was still tagged as "Reviewing" and we typically filter out the tickets that you are reviewing when we're looking for things to work on. I just fixed the "local variable 'reg' referenced before assignment" error.

**Comment by WaBirder57** [comment]
@ebskopin Elliott can you test this please.

**Comment by ebskopin** [comment]
This is now working as intended. Thanks.
