### ISSUE TITLE
Indexer should handle SERVER_UNAVAILABLE response from Salesforce

### ISSUE THREAD

**Issue by WaBirder57** [washingtontrails/vms#69]
This morning, 4/2, the VMS Staging website is not showing any work parties.  This is preventing us from testing.

**Comment by davisagli** [comment]
Fixed. The indexer had aborted because Salesforce was temporarily unavailable. I just restarted it.

We should make the indexer robust enough to handle this by just waiting and trying again later. For my reference, here's the traceback:
```
Traceback (most recent call last):
  File "/usr/local/pyramid/vms/bin/indexer", line 48, in <module>
    sys.exit(vms.commands.indexer.main())
  File "/usr/local/pyramid/vms/src/vms/commands/indexer.py", line 237, in main
    run_indexer(app)
  File "/usr/local/pyramid/vms/src/vms/commands/indexer.py", line 179, in run_indexer
    salesforce = SalesforceClient(settings)
  File "/usr/local/pyramid/vms/src/vms/salesforce_client.py", line 25, in __init__
    self.login()
  File "/usr/local/pyramid/vms/src/vms/salesforce_client.py", line 32, in login
    sandbox=True,
  File "/usr/local/pyramid/vms/eggs/simple_salesforce-0.65.1-py2.7.egg/simple_salesforce/api.py", line 74, in __init__
    proxies=self.proxies)
  File "/usr/local/pyramid/vms/eggs/simple_salesforce-0.65.1-py2.7.egg/simple_salesforce/login.py", line 115, in SalesforceLogin
    code=except_code, message=except_msg))
simple_salesforce.login.SalesforceAuthenticationFailed: SERVER_UNAVAILABLE: server temporarily unavailable
```

**Comment by davisagli** [comment]
Reopening because I still need to make it handle when Salesforce is unavailable.

**Comment by davisagli** [comment]
I increased the number of retries for starting the indexer, so supervisor is less likely to give up and leave it stopped.
